### ISSUE TITLE
Provide link to source for the included jars

### ISSUE THREAD

**Issue by danielegobbetti** [SASAbus/SASAbus#12]
Needed for #2 

Currently a build by fdroid gives the following warnings:
WARNING: Found JAR file at app/libs/dm-web-lib-1.0.20140410.jar
WARNING: Found JAR file at app/libs/org-json-parser-2013-12-13.jar
WARNING: Found JAR file at app/libs/sasabus-backend-lib-1.0.20140417.jar
WARNING: Found JAR file at app/libs/dm-xml-json-lib-1.0.20140408.jar
WARNING: Found JAR file at app/libs/sasabus-opendata-lib-1.0.20140329.jar
WARNING: Found JAR file at app/libs/sasabus-realtime-1.0.20140508.jar
WARNING: Found JAR file at app/libs/commons-io-2.4.jar

The jars may remain in the repository (fdroid may be told to discard them), but links to the corresponding repos should be provided.

**Comment by markuswindegger** [comment]
Is it not enaugh to have all the source in the jar files? has there to be the link to the repos?

~amrkus

**Comment by danielegobbetti** [comment]
Afaik fdroid build bot wants to have a build script for libraries as well, but I may be wrong.
--

**Comment by dejdav** [comment]
All of the following libraries have been removed with [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0) and are no longer in use.

- commons-io-2.4.jar
- dm-web-lib-1.0.20140410.jar
- dm-xml-json-lib-1.0.20140408.jar
- org-json-parser-2013-12-13.jar
- sasabus-backend-lib-1.0.20140417.jar
- sasabus-opendata-lib-1.0.20140329.jar
- sasabus-realtime-1.0.20140508.jar
