### ISSUE TITLE
App crashes when departures textview is empty

### ISSUE THREAD

**Issue by AlexLardschneider** [SASAbus/SASAbus#17]
Clicking on refresh in the bus stops fragment results in a NullPointerException dialog when the "Departures" EditText is empty.
Clicking in "Searching..." afterwards crashes the app due to a ClassCastException.

**Comment by dejdav** [comment]
Fixed with [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0).
