### ISSUE TITLE
UI elements are clickable through the line path list

### ISSUE THREAD

**Issue by AlexLardschneider** [SASAbus/SASAbus#18]
UI elements like DatePicker or lines list in the bus lines fragment are clickable through the lines path list appearing when clicking on a driving line (see attached screenshot). Using View.GONE instead of View.INVISIBLE would be a possible fix.

![screenshot_2015-11-26-18-20-41](https://cloud.githubusercontent.com/assets/10795750/11428363/cddd609a-946a-11e5-8d53-ac375669c6af.png)

**Comment by noctho** [comment]
Fixed with e3554b8427ba5affe5bb11e72832c3c44a7fab68
