### ISSUE TITLE
Creating release cycle

### ISSUE THREAD

**Issue by markuswindegger** [SASAbus/SASAbus#20]
With the community implementing a sort of release cycle of SASAbus, like the first monday every month ist the last day to commit for the monthly release. If there are no commits, there will be no new release.

**Comment by dejdav** [comment]
That's a good idea. The release dates for 2016 would be on the following Mondays:
- Aug 1
- Sep 5
- Oct 3
- Nov 7
- Dec 5

We should consider to release some beta versions on other dates though (in order to let some users test the new versions).
