### ISSUE TITLE
Creating rules for tagging

### ISSUE THREAD

**Issue by markuswindegger** [SASAbus/SASAbus#22]

**Comment by danielegobbetti** [comment]
Details about how tags are understood by fdroid for auto building updates:
https://f-droid.org/manual/html_node/Auto-Update-Mode.html

**Comment by dejdav** [comment]
#### Releases
I'd suggest to tag a release (ready to be published on the Google Play Store) with a `v` (version) as prefix, followed by the app version name, e. g. `v2.1.0` for the version `2.1.0`.

#### Beta versions
For beta versions I'd append `-beta`, followed by an incrementing number (starting at `1`). This means if we are currently at version `2.0.0` and are focusing on developing `2.0.1`, then the first beta would have the tag `v2.0.1-beta1`, the next `v2.0.1-beta2`, etc. until the public release `v2.0.1`.
