### ISSUE TITLE
Crash when Bluetooth is turned on while SASAbus is running

### ISSUE THREAD

**Issue by markuswindegger** [SASAbus/SASAbus#24]
12-07 11:10:16.805 18675-18675/? E/BeaconHandler: Started listening for beacons
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime: FATAL EXCEPTION: main
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime: Process: it.sasabz.android.sasabus, PID: 19300
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime: java.lang.RuntimeException: Unable to create service it.sasabz.sasabus.beacon.BeaconScannerService: java.lang.UnsupportedOperationException
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap4(ActivityThread.java)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:  Caused by: java.lang.UnsupportedOperationException
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at java.util.Collections$UnmodifiableCollection.add(Collections.java:932)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at it.sasabz.sasabus.beacon.BeaconObserver.startListening(BeaconObserver.java:77)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at it.sasabz.sasabus.beacon.BeaconScannerService.onCreate(BeaconScannerService.java:28)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap4(ActivityThread.java) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
12-07 11:10:16.807 19300-19300/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
12-07 11:10:16.838 18675-18675/? E/BeaconHandler: onBeaconServiceConnect()

**Comment by AlexLardschneider** [comment]
Happens daily on my S5

**Comment by dejdav** [comment]
Fixed with [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0).
