### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by mwallnoefer** [SASAbus/SASAbus#25]
Button "Show Departures" in the bus stop details (balloon) on the map has not been language-localised yet.

**Comment by dejdav** [comment]
With the new version of SASAbus these string resources don't exist anymore. Thus this isn't an issue anymore. The update was applied in [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0).
