### ISSUE TITLE
Readd support for F-Droid

### ISSUE THREAD

**Issue by AlexLardschneider** [SASAbus/SASAbus#26]
We should consider readding support for F-Droid or at least a version which does not depend on Google Play Services, probably by readding a build flavor for F-Droid and one for the Play Store.

Google Analytics can be replaced by the mock Analytics implementation which was previously added by @danielegobbetti with issue #13, but GCM probably has to be replaced entirely by another system to still receive push notifications on F-Droid builds. Also Crashlytics needs to be replaced or removed as it is not open source.

**Comment by AlexLardschneider** [comment]
Support for F-Droid has been readded in 30632984885574b77fb71620579f69cb00f88bc7

**Comment by danielegobbetti** [comment]
Will do!
