### ISSUE TITLE
GPS Search makes map useless when no GPS fix 

### ISSUE THREAD

**Issue by ohnewein** [SASAbus/SASAbus#4]
When I use the map to select a bus stop, the map performes a GPS search. Even if I disable GPS sensor on the device.

While searching GPS fix the map is not usable. It is not possible to select a bus stop.

**Comment by ohnewein** [comment]
I still have this problem. But maybe I am just unable to understand how the map works.

@davidebz can we look at it, next time you are at TIS?

**Comment by markuswindegger** [comment]
I think I close this issue, as there we have a new version which fixes this. This version is rolled out as beta an as soon as possible we provide a stable version for this too...
