### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by ohnewein** [SASAbus/SASAbus#7]
Would be useful to have some data available when offline.

In this way people on the road, without good internet connection, could at least get basic time table information.

**Comment by davidebz** [comment]
SASAbus should work offline. Maps and planned timetables are downloaded for offline use. Only real-time data is obviously absent. What kind of problem have you with offline usage?

**Comment by ohnewein** [comment]
Hi Davide, I made a quick test pitting the smartphone to airplane mode and SASAbus didn't give any data as results.

**Comment by davidebz** [comment]
Open the application in online-mode and check if there is a android 
notification about updating the timetables.

**Comment by noctho** [comment]
Hi,

I also tried to search for a bus connection while being oflline. The result
was an error (UnknownHostException). I have all the updated timetables.

~thomas
Am 23.04.2015 11:06 schrieb "davidebz" <notifications@github.com>:

**Comment by markuswindegger** [comment]
Connections are calculated by a routing engine and available only online and not offline. Offline the afford (a part some spevial algorithms but not compatible wih our datamodels) for calculating routes from scratch isn't possible with the smartphones (a part some new ones).
It would be have an unusual impact on the batteries too.

Am 23. April 2015 12:40:53 MESZ, schrieb noctho <notifications@github.com>:
>Hi,
>
>I also tried to search for a bus connection while being oflline. The
>result
>was an error (UnknownHostException). I have all the updated timetables.
>
>~thomas
>Am 23.04.2015 11:06 schrieb "davidebz" <notifications@github.com>:
>
>>
>> Open the application in online-mode and check if there is a android
>> notification about updating the timetables.
>>
>>
>> On 23/04/2015 00:20, Patrick Ohnewein wrote:
>> >
>> > Hi Davide, I made a quick test pitting the smartphone to airplane
>mode
>> > and SASAbus didn't give any data as results.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> >
><https://github.com/SASAbus/SASAbus/issues/7#issuecomment-95355064>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SASAbus/SASAbus/issues/7#issuecomment-95499408>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SASAbus/SASAbus/issues/7#issuecomment-95530874

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ohnewein** [comment]
Ohhh. I noticed now, that I had an outdated developer version installed.

Offline information of time table works!

**Comment by ohnewein** [comment]
On some functions, like parking data, I get an error message like described by Thomas. This should be handled in a user friendlier way.

**Comment by AlexLardschneider** [comment]
Fixed with [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0).
