### ISSUE TITLE
current master not buildable

### ISSUE THREAD

**Issue by danielegobbetti** [SASAbus/SASAbus#8]
Hi,

it seems that current master is not buildable, as some resources are missing. This is the output when running gradle assembleDebug in a fresh git clone:

```
SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:47: error: cannot find symbol
		this.apiUrl = context.getResources().getString(R.string.survey_api_url);
		                                                       ^
  symbol:   variable survey_api_url
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:48: error: cannot find symbol
		this.apiUser = context.getResources().getString(R.string.survey_api_user);
		                                                        ^
  symbol:   variable survey_api_user
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:49: error: cannot find symbol
		this.apiPassword = context.getResources().getString(R.string.survey_api_password);
		                                                            ^
  symbol:   variable survey_api_password
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/gson/bus/service/BusApiService.java:44: error: cannot find symbol
		this.apiUrl = context.getResources().getString(R.string.bus_api_url);
		                                                       ^
  symbol:   variable bus_api_url
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:255: error: cannot find symbol
			this.getOpenDataStorage().asyncDownloadSASAbusOpenDataToLocalStore(this.getString(R.string.opendata_server_url),
			                                                                                          ^
  symbol:   variable opendata_server_url
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:302: error: cannot find symbol
		final String downloadzip = MainActivity.this.getString(R.string.maptiles_server_url) + "/" + this.OSM_ZIP_NAME;
		                                                               ^
  symbol:   variable maptiles_server_url
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:427: error: cannot find symbol
			this.getOpenDataStorage().asyncReadRemoteVersionDate(this.getString(R.string.opendata_server_url),
			                                                                            ^
  symbol:   variable opendata_server_url
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/ui/busstop/NextBusFragment.java:412: error: cannot find symbol
	   getActivity().registerReceiver(beaconBusstopReceiver, new IntentFilter(getString(R.string.station_beacon_uid)));
	                                                                                            ^
  symbol:   variable station_beacon_uid
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/beacon/bus/trip/TripNotificationAction.java:79: error: cannot find symbol
				.setContent(getBaseNotificationView(curentTrip)).setSmallIcon(R.drawable.ic_notification).setContentIntent(pendingIntent)
				                                                                        ^
  symbol:   variable ic_notification
  location: class drawable
SASAbus/app/src/main/java/it/sasabz/sasabus/beacon/busstop/BusStopBeaconHandler.java:50: error: cannot find symbol
		Intent intent = new Intent(mApplication.getApplicationContext().getString(R.string.station_beacon_uid));
		                                                                                  ^
  symbol:   variable station_beacon_uid
  location: class string
SASAbus/app/src/main/java/it/sasabz/sasabus/data/orm/NewsList.java:65: error: cannot find symbol
         String newsserver = this.context.getString(R.string.newsserverjson);
                                                            ^
  symbol:   variable newsserverjson
  location: class string
```

**Comment by markuswindegger** [comment]
You build it with android studio or eclipse?

Am 23. November 2015 16:24:40 MEZ, schrieb Daniele Gobbetti <notifications@github.com>:
>Hi,
>
>it seems that current master is not buildable, as some resources are
>missing. This is the output when running gradle assembleDebug in a
>fresh git clone:
>
>```
>SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:47:
>error: cannot find symbol
>		this.apiUrl =
>context.getResources().getString(R.string.survey_api_url);
>		                                                       ^
>  symbol:   variable survey_api_url
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:48:
>error: cannot find symbol
>		this.apiUser =
>context.getResources().getString(R.string.survey_api_user);
>		                                                        ^
>  symbol:   variable survey_api_user
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/gson/survey/service/SurveyApiService.java:49:
>error: cannot find symbol
>		this.apiPassword =
>context.getResources().getString(R.string.survey_api_password);
>		                                                            ^
>  symbol:   variable survey_api_password
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/gson/bus/service/BusApiService.java:44:
>error: cannot find symbol
>		this.apiUrl = context.getResources().getString(R.string.bus_api_url);
>		                                                       ^
>  symbol:   variable bus_api_url
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:255:
>error: cannot find symbol
>			this.getOpenDataStorage().asyncDownloadSASAbusOpenDataToLocalStore(this.getString(R.string.opendata_server_url),
>			                                                                    
>                     ^
>  symbol:   variable opendata_server_url
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:302:
>error: cannot find symbol
>		final String downloadzip =
>MainActivity.this.getString(R.string.maptiles_server_url) + "/" +
>this.OSM_ZIP_NAME;
>		                                                               ^
>  symbol:   variable maptiles_server_url
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/ui/MainActivity.java:427:
>error: cannot find symbol
>			this.getOpenDataStorage().asyncReadRemoteVersionDate(this.getString(R.string.opendata_server_url),
>			                                                                    
>       ^
>  symbol:   variable opendata_server_url
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/ui/busstop/NextBusFragment.java:412:
>error: cannot find symbol
>	   getActivity().registerReceiver(beaconBusstopReceiver, new
>IntentFilter(getString(R.string.station_beacon_uid)));
>	                                                                      
>                     ^
>  symbol:   variable station_beacon_uid
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/beacon/bus/trip/TripNotificationAction.java:79:
>error: cannot find symbol
>				.setContent(getBaseNotificationView(curentTrip)).setSmallIcon(R.drawable.ic_notification).setContentIntent(pendingIntent)
>				                                                                   
>    ^
>  symbol:   variable ic_notification
>  location: class drawable
>SASAbus/app/src/main/java/it/sasabz/sasabus/beacon/busstop/BusStopBeaconHandler.java:50:
>error: cannot find symbol
>		Intent intent = new
>Intent(mApplication.getApplicationContext().getString(R.string.station_beacon_uid));
>		                                                                     
>            ^
>  symbol:   variable station_beacon_uid
>  location: class string
>SASAbus/app/src/main/java/it/sasabz/sasabus/data/orm/NewsList.java:65:
>error: cannot find symbol
>   String newsserver = this.context.getString(R.string.newsserverjson);
>                                                            ^
>  symbol:   variable newsserverjson
>  location: class string
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SASAbus/SASAbus/issues/8

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by danielegobbetti** [comment]
```
./gradlew assembleDebug
```

**Comment by markuswindegger** [comment]
Ok...i think tomorrow i will have some minute to retest...because actual beta version was built with gradle and android studio...

Thanks!
~markus

Am 23. November 2015 16:43:01 MEZ, schrieb Daniele Gobbetti <notifications@github.com>:
>```
>./gradlew assembleDebug
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SASAbus/SASAbus/issues/8#issuecomment-158972945

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by danielegobbetti** [comment]
No rush, when it gets fixed I can look into updating the fdroid metadata :)

**Comment by danielegobbetti** [comment]
I know I said no rush :) , but I would like to know wheter you had time to look at this issue.

Best,
Daniele

**Comment by noctho** [comment]
Now you should be able to build it.

**Comment by danielegobbetti** [comment]
It works with d7d514fa170434537ce425bb17d57727c2f9d92f, thanks!
